def merge(body: dict, claude_output: dict, dossier: dict) -> dict:
    content = dict(body)
    content["we_see_you"] = claude_output.get("WE_SEE_YOU", "")
    content["the_gap"] = claude_output.get("THE_GAP", "")
    content["strategic_insight"] = claude_output.get("STRATEGIC_INSIGHT", "")
    content["chapter_experiment"] = claude_output.get("CHAPTER_EXPERIMENT", "")
    content["linkedin_post_1"] = claude_output.get("LINKEDIN_POST_1", "")
    content["linkedin_post_2"] = claude_output.get("LINKEDIN_POST_2", "")
    content["linkedin_post_3"] = claude_output.get("LINKEDIN_POST_3", "")
    content["email_hooks"] = claude_output.get("EMAIL_HOOKS", "")
    content["diagnosis"] = claude_output.get("DIAGNOSIS", "")

    content["author_name"] = dossier.get("author_name", "")
    content["book_title"] = dossier.get("book_title", "")
    content["book_publisher"] = dossier.get("book_publisher", "")
    content["book_publication_date"] = dossier.get("book_publication_date", "")
    content["amazon_rank"] = dossier.get("book_bsr", "")
    content["review_count"] = dossier.get("book_review_count", "")
    content["avg_rating"] = dossier.get("book_avg_rating", "")
    content["linkedin_followers"] = str(dossier.get("linkedin_follower_count", 0))
    content["current_role"] = dossier.get("linkedin_current_role", "")
    content["current_company"] = dossier.get("linkedin_current_company", "")
    content["cluster"] = claude_output.get("CLUSTER", "Discovery")
    content["identity_split"] = claude_output.get("IDENTITY_SPLIT", "No")
    return content
