def build(inputs, profile, posts, articles, amazon, goodreads, website, press, podcasts, books) -> dict:
    return {
        "author_name": inputs["author_name"],
        "book_title": inputs["book_title"],
        "amazon_url": inputs["amazon_url"],
        "website_url": inputs["website_url"],
        "linkedin_headline": profile.get("headline", ""),
        "linkedin_about": profile.get("about", ""),
        "linkedin_current_role": profile.get("position", [{}])[0].get("title", "") if profile.get("position") else "",
        "linkedin_current_company": profile.get("position", [{}])[0].get("companyName", "") if profile.get("position") else "",
        "linkedin_follower_count": profile.get("followersCount", 0),
        "linkedin_connection_count": profile.get("connectionsCount", 0),
        "linkedin_experience": profile.get("experience", []),
        "linkedin_education": profile.get("education", []),
        "linkedin_posts": posts,
        "linkedin_articles": articles,
        "book_publication_date": amazon.get("publication_date", ""),
        "book_publisher": amazon.get("publisher", ""),
        "book_avg_rating": amazon.get("avg_rating", ""),
        "book_review_count": amazon.get("review_count", ""),
        "book_bsr": amazon.get("bsr", ""),
        "book_description": amazon.get("description", ""),
        "book_editorial_reviews": amazon.get("editorial_reviews", ""),
        "amazon_top_reviews": amazon.get("top_reviews", []),
        "goodreads_avg_rating": goodreads.get("avg_rating", ""),
        "goodreads_review_count": goodreads.get("review_count", ""),
        "goodreads_shelves": goodreads.get("shelves", []),
        "goodreads_top_reviews": goodreads.get("top_reviews", []),
        "website_about_text": website.get("about_text", ""),
        "website_has_email_capture": website.get("has_email_capture", False),
        "website_has_speaking_page": website.get("has_speaking_page", False),
        "website_has_podcast": website.get("has_podcast", False),
        "website_has_blog": website.get("has_blog", False),
        "website_blog_posts": website.get("blog_posts", []),
        "press_coverage": press,
        "podcast_appearances": podcasts,
        "all_known_books": books,
    }
